# Generated by Django 5.0 on 2023-12-13 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_name', models.CharField(blank=True, max_length=255)),
                ('end_date', models.DateField()),
                ('ad_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Advertisements',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('max_daily_visitors', models.PositiveIntegerField(default=0)),
                ('visitor_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='DailyVisitorCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_date', models.DateTimeField(blank=True)),
                ('visitor_count', models.PositiveIntegerField(default=0)),
                ('advertisement', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ads.advertisement')),
                ('location', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ads.location')),
            ],
            options={
                'verbose_name_plural': 'Daily Visitor Count',
            },
        ),
        migrations.AddField(
            model_name='advertisement',
            name='locations',
            field=models.ManyToManyField(related_name='advertisements', to='ads.location'),
        ),
    ]
